site_name: CATBench Documentation
site_url: https://odgaard.github.io/catbench/
site_description: A benchmarking framework for evaluating computational performance and energy efficiency
repo_url: https://github.com/odgaard/catbench
repo_name: odgaard/catbench

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started.md
    - Quick Start: getting-started.md#basic-usage
  - User Guide:
    - Available Benchmarks: benchmarks.md
    - Examples: examples.md
    - API Reference: api-reference.md
  - Deployment:
    - Single Node: deployment.md#single-node-deployment
    - Cluster Setup: deployment.md#cluster-deployment
    - Docker: deployment.md#docker-deployment-options
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/odgaard/catbench
  generator: false